###
# Dimension
dim: 3

###
# Number of orientations.
num_oris: 20

###
# Number of grains.
num_grains: 40000

###
# The height of the domain (z-direction domain size). Unit: [mm]
domain_height: 0.1

###
# The width of the domain (y-direction domain size). Unit: [mm]
domain_width: 0.4

###
# The length of the domain (y-direction domain size). Unit: [mm]
domain_length: 1.

###
# Melting point. Unit: [K]
T_melt: 1700.
 
###
# Ambient temperature. Unit: [K]
T_ambient: 300.
 
###
# Density. Unit: [kg/mm^3]
rho: 8.08e-6
  
###
# Specific heat. Unit: [J/(kg*K)]
c_p: 770.
 
###
# Laser power. Unit: [W]
power: 200.
 
###
# Laser power fraction. Unit: []
power_fraction: 0.4
 
###
# Laser beam size. Unit: [mm]
r_beam: 0.1
 
###
# Emissivity. Unit: []
emissivity: 0.2
 
###
# Stefan–Boltzmann constant. Unit: [W/(mm^2*K^4)]
SB_constant: 5.67e-14
 
###
# Heat convection coefficient. Unit: [W/(mm^2*K)]
h_conv: 1.e-4
  
###
# Thermal conductivity. Unit: [W/(mm*K)]
kappa_T: 1.e-2
 
###
# Gas constant. Unit: [J/(Mol*K)]
gas_const: 8.3
  
###
# Qg (phase-field parameter). Unit: [J/Mol]
Qg: 1.4e+5
   
###
# L0 (phase-field parameter). Unit: [mm^4/(J*s)]
L0: 3.5e+12

###
# kappa_g (phase-field parameter). Unit: [J/mm]
kappa_g: 2.77e-9
 
###
# m_g (phase-field parameter). Unit: [J/mm^3]
m_g: 2.4e-4
 
###
# anisotropy (phase-field parameter). Unit: []
anisotropy: 0.15
 
###
# An ad-hoc parameter (phase-field parameter). Unit: []
ad_hoc: 1.

###
# The time step for integration. Unit: [s]
dt: 2.e-7

###
# Out put steps.
write_sol_interval:
  value: 500
  unit: N/A 
